#
# This file is part of Tedium.
#
# Copyright (C) 2020 Jared Boone <jared@sharebrained.com>
# SPDX-License-Identifier: BSD-3-Clause

iso_loopback: iso_loopback.cpp
	g++ -g -o iso_loopback iso_loopback.cpp -lusb-1.0

clean:
	rm iso_loopback
